
// Objective-C API for talking to the following Go packages
//
//	github.com/iancanderson/gandermerge/mobile
//	github.com/hajimehoshi/ebiten/v2/mobile/ebitenmobileview
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gandermerge_FRAMEWORK_H__
#define __Gandermerge_FRAMEWORK_H__

#include "Gandermergemobile.objc.h"
#include "Ebitenmobileview.objc.h"
#include "Universe.objc.h"

#endif
